# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71d27fd0223988a0ed0cb8ba6f3cb67d73c49dc615f092555c39fa2c4018ee300f418254c5fb89b7521ec5c206cc5530b667376b74076a5a7ceed965f35aee51

test:
  secret_key_base: 8c46f982d9484f7494500934b9660bc4627fbf8108dbf05e3723c30118426f7317a8c900fbf318c1a25dbd9c09fc11406892e2cbaa9c3bd5acb84fe5add53536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
